### ISSUE TITLE
App crushes after installation

### ISSUE THREAD

**Issue by furkanedu** [MadeInMoon/template-meteor-react#1]
Hi, I have cloned your repo, npm installed , meteored and all I can see is the background image, nothing else. From the console , there seems to be an error only , which is ;
﻿
*****  modules-runtime.js:420 Uncaught Error: Cannot find module '/client/app/Theme' *****

I am already trying to figure out, but you might know reason of this error or why I only see a page with your brown background image .
Thanks for the repo btw.
﻿

**Comment by MadeInMoon** [comment]
Oh sorry, the folder 'app' was called 'App' before, and github was keeping both of them..

The fix : http://stackoverflow.com/questions/6899582/i-change-the-capitalization-of-a-directory-and-git-doesnt-seem-to-pick-up-on-it

-----------

I will do my maximum to improve this repo during the following weeks, so sorry if some things are not clean or clear! And don't hesitate to collaborate, to give advices etc.. ;)

**Comment by furkanedu** [comment]
Good luck man, If I can I ll help you about improvements too.

**Comment by furkanedu** [comment]
BTW, why did you seperate some methods under lib directory ? I mean there are some methods under the server/methods and lib/collections/methods . Why to seperate ? What is the difference ?

**Comment by MadeInMoon** [comment]
Good question.. 

This is my actual thinking:


With Meteor we can easily build an universal javascript app, which share all the methods into a shared folder like `lib/`, and using `Meteor.isClient` / `Meteor.isServer`.

But this ease could leads to complex problems if your app gets bigger, or if you have multiple clients working with the same server part. Exemple: 
- 1 server 
- 1 client (admin website)
- 1 client (users on ios & android)

Most of time, the server and both clients can or have to share same data, with real-time. Universal javascript won't be best solution in this case. 

That is what [Mantra](https://github.com/kadirahq/mantra), and a lot of developpers, are pointing at. 

-------

If we look the [sendverificationemail](http://docs.meteor.com/#/full/accounts_sendverificationemail), it is a server-side method only. I was saying to me, following the concept of mantra (look this [architecture](https://github.com/mantrajs/mantra-sample-blog-app)), that all the server methods (only)  will be in `server/methods/`

Same idea in `client/api` (maybe we should rename it `client/methods`). 

And all the collection-methods in `lib/collections/methods`


---------

 I also think we should maybe re-organize few folders or folders-names for it can be cleaner.. I will think&work on it tonight and days coming !

Tell me what do you think about this conception!

**Comment by furkanedu** [comment]
Hey man , changing the name to client/methods or moving it to lib/ directory is a good idea. Recently, I have changed my mind to use flow-router, since it is easier. But I ll check your changes, I really liked your ambition about this project.
